# Generated by Django 3.2.5 on 2021-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='news_pics'),
        ),
    ]
