# Generated by Django 3.2.5 on 2021-07-19 14:32

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=django.db.models.fields.NullBooleanField, null=True, upload_to='post_pics'),
        ),
    ]
