# Generated by Django 3.2.5 on 2021-07-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20210721_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
