# Generated by Django 3.2.5 on 2021-07-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
