# Generated by Django 3.2.5 on 2021-07-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
